version: '3'
services: 
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '5050:80'
  postgres: 
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BioPhysPrj1324
  node:
    build:
      dockerfile: Dockerfile.dev
      context: ./node
    volumes:
      - /app/node_modules
      - ./node :/app
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=BioPhysPrj1324
      - DB_HOST=postgres
      - DB_SCHEMA=public 
    depends_on:
      - postgres
  react:
    build:
      dockerfile: Dockerfile.dev
      context: ./react
    volumes:
      - /app/node_modules
      - ./react:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_STATIC_URI=
      - REACT_APP_GRAPHQL_URI=graphql